### ISSUE TITLE
FsUnit  not working with XUnit pre release version

### ISSUE THREAD

**Issue by unuunc** [fsprojects/FsUnit#34]
it is not able to find Xunit asserts , asking for adding xunit library which is already added.

**Comment by larjo** [comment]
Yes, FsUnit only works with xunit 1.9.1. Specifically it doesn't work with xunit 1.9.2 which is the latest stable release. That is unfortunate since I am also using FsCheck which requires xunit >= 1.9.2.

My workaround is to use https://github.com/fsprojects/Paket to reference the files CustomMatchers.fs and FsUnit.fs directly from github.

**Comment by sergey-tihon** [comment]
I think that would be better to release FsUnit with dependency on exact version of NUnit\XUnit which where tested and works as expected:
Replace
```
      <dependency id="NUnit" version="2.6.3" />
```
to 
```
      <dependency id="NUnit" version="[2.6.3]" />
```

**Comment by larjo** [comment]
Yes, and

    <dependency id="xunit" version="[1.9.1, 3.0)" />

to

    <dependency id="xunit" version="[1.9.1]" />

How much work would you think there is to make FsUnit compatible with xunit >= 1.9.2 (and  NUnit >= 2.6.4)?

**Comment by ctaggart** [comment]
The error I get when trying to upgrade Xunit to prerelease is:
```
error FS0074: The type referenced through 'Xunit.Assert' is defined in an assembly that is not referenced. You must add a reference to assembly 'xunit'.
```
Info on upgrading to v2 is here:
http://xunit.github.io/docs/test-migration.html

**Comment by et1975** [comment]
Now that xUnit 2.0 is RTM this is a bit of an urgent issue IMHO.

**Comment by sergey-tihon** [comment]
@et1975 We need to contact @dmohl somehow.
He is only owner of NuGet package

**Comment by et1975** [comment]
Is that the only issue though? When I fixed it in my fork I noticed that the target framework is 3.5, which xUnit 2.0 does not support anymore. I had to change that for my local build, but I don't know what are the goals of FsUnit in this regard.

**Comment by nathanaeljones** [comment]
Has anyone pushed up a temporary fork to nuget to work around this issue?

**Comment by brodyberg** [comment]
This is still happening out of the box :-/

**Comment by sergey-tihon** [comment]
Please try [FsUnit.xUnit 1.3.1-beta](https://www.nuget.org/packages/FsUnit.xUnit/1.3.1-beta).
It should work with `xunit v1.9.2`, at least I hope so.
Let me know if it is not, or if you find any issues.

**Comment by sergey-tihon** [comment]
Please try `xUnit 2.0` support [FsUnit.xUnit 1.4.0-beta](https://www.nuget.org/packages/FsUnit.xUnit/1.4.0-beta)
